### ISSUE TITLE
FileZilla upload failed

### ISSUE THREAD

**Issue by musahi0128** [RuslanUC/TelegramFTP#2]
Hi, thank you for your software. I really love the concept, and your setup documentation is easy to follow.

Unfortunately, I run into following issue.
I tried to upload a dummy file using FileZilla, 50MiB in size. The upload seems to be working at first, saying it is 100% uploaded.
But after a while it stuck at 100% and did not move to Successful transfer tab.
I notice in the Telegram channel, some files named "file" showed up with size 16+16+16+2 MiB respectively, and those files shows up 3 times, so 12 files in total, 150 MiB in size.
After sometimes, the transfer in FileZilla move to Failed transfers tab with reason=timeout.
And after a while, I can see in the terminal following error
```
root@mush:~/TelegramFTP# python3 ./main.py
FTP server starting...
Task exception was never retrieved
future: <Task finished name='Task-2329' coro=<MongoDBUserManager.notify_logout() done, defined at /root/TelegramFTP/ftp/server.py:113> exception=ValueError('Too many releases')>
Traceback (most recent call last):
  File "/root/TelegramFTP/ftp/server.py", line 114, in notify_logout
    self.available_connections[user].release()
  File "/root/TelegramFTP/ftp/server.py", line 171, in release
    raise ValueError("Too many releases")
ValueError: Too many releases
```
Please help me to fix the issue. Thanks!

**Comment by RuslanUC** [comment]
Hi. Try to increase/disable timeout: Edit -> Settings -> Connection -> Timeout in seconds, set it to 0.
